[package]
name = "jlog"
version = "0.2.0"
edition = "2024"

[dependencies]
eframe = "0.31"
ssh2 = "0.9"
rfd = "0.15"
crossbeam-channel = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
regex = "1.0"
anyhow = "1.0"
once_cell = "1.19"
base64 = "0.22"
